CREATE TABLE `test` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `random` INT UNSIGNED NOT NULL DEFAULT 0,
    `name` VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;
CREATE INDEX `random` ON `test`(`random`);
